apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order
          image: opentelemetry-nodejs-example-order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3001
          env:
            - name: DATABASE_URL
              value: mongodb://host.docker.internal:27017/orders
            - name: HONOAPP_URL
              value: http://user-service:3004
            - name: USER_SERVICE_URL
              value: http://user-service:3004
            - name: PRODUCT_SERVICE_URL
              value: http://product-service:3003
            - name: OTEL_NODE_RESOURCE_DETECTORS
              value: env,host,os
            - name: OTEL_SERVICE_NAME
              value: order-service
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://$(HOST_IP):4318
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 3001
      targetPort: 3001
