apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default  # change if needed
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      filelog:
        include: 
          - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        exclude:
          - /var/log/pods/kube-system*/*/*.log
          - /var/log/pods/*otel-collector*/*/*.log
        start_at: end
        operators:
          - type: container

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1000
      batch/traces:
        timeout: 1s
        send_batch_size: 100
      attributes:
        actions:
          - key: cluster
            value: "eks-dev"
            action: insert
          - key: environment
            value: "production"
            action: insert
      attributes/traces:
        actions:
          - key: cluster
            value: "eks-dev"
            action: insert
          - key: environment
            value: "production"
            action: insert

    exporters:
      # Victoria Logs for logs
      otlphttp/logs:
        endpoint: "http://vlc-victoria-logs-cluster-vlinsert.monitoring.svc.cluster.local:9481/insert/opentelemetry"
        tls:
          insecure: true

      # Grafana Tempo for traces
      otlp/tempo:
        endpoint: "http://redenv-tempo.monitoring.svc.cluster.local:4317"
        tls:
          insecure: true
        headers:
          # Optional: Add authentication if needed
          # authorization: "Bearer YOUR_TOKEN"

      # Alternative HTTP endpoint for Tempo
      otlphttp/tempo:
        endpoint: "http://redenv-tempo.monitoring.svc.cluster.local:4318"
        tls:
          insecure: true


          

      debug:
        verbosity: detailed   # options: basic, normal, detailed

    service:
      pipelines:
        logs:
          receivers: [filelog] 
          processors: [batch, attributes]
          exporters: [otlphttp/logs]
        
        traces:
          receivers: [otlp]
          processors: [batch/traces, attributes/traces]
          exporters: [otlp/tempo,otlphttp/tempo, debug] 