apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user
          image: opentelemetry-nodejs-example-main-user:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3004
          env:
            - name: DATABASE_URL
              value: mongodb://host.minikube.internal:27017/users
            - name: HONOAPP_URL
              value: http://hono-service:3000
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector:4318
            - name: OTEL_NODE_RESOURCE_DETECTORS
              value: env,host,os
            - name: OTEL_SERVICE_NAME
              value: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - port: 3004
      targetPort: 3004
